FROM envoyproxy/envoy-dev:latest

ADD envoy.yaml /etc/envoy.yaml

RUN apt-get update && apt-get -q install -y \
    curl

ENV SERVICE_NAME

ADD start_envoy.sh /start_envoy.sh

RUN chmod +x /start_envoy.sh

ENTRYPOINT ["/bin/sh"]

CMD ["start_envoy.sh"]
